/**
 * Adds a `scheduled` handler so Cloudflare Cron Triggers have something to call.
 *
 * @sveltejs/adapter-cloudflare only emits `fetch`, and it writes that bundle to
 * whatever `main` points at (see its index.js: `worker_dest = wrangler_config.main`),
 * so a hand-written wrapper at `main` gets overwritten on every build. Instead we
 * run after the adapter: move its bundle aside, then write a wrapper in its place
 * that re-exports `fetch` and adds `scheduled`.
 *
 * The bundle has to stay in the same directory it was written to: the adapter
 * emits imports relative to `main`, so moving it into a subdirectory breaks
 * `./.svelte-kit/output/server/index.js` and the build fails to resolve.
 */
import { existsSync, renameSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const MAIN = resolve('worker.js');
const CORE = resolve('worker-core.js');

if (!existsSync(MAIN)) {
	console.error(`wrap-worker: ${MAIN} not found — did the adapter run?`);
	process.exit(1);
}

renameSync(MAIN, CORE);

writeFileSync(
	MAIN,
	`// Generated by scripts/wrap-worker.mjs — do not edit.
import worker from './worker-core.js';

async function runCron(env, ctx, task) {
	if (!env.CRON_SECRET) {
		console.error('cron: CRON_SECRET is not set, skipping');
		return;
	}

	const base = env.APP_URL ?? 'https://affiliates.getbee.app';
	const request = new Request(base + '/api/cron/sync?task=' + task, {
		method: 'POST',
		headers: { authorization: 'Bearer ' + env.CRON_SECRET }
	});

	const response = await worker.fetch(request, env, ctx);
	const body = await response.text();
	console.log('cron ' + task + ': ' + response.status + ' ' + body.slice(0, 500));
}

export default {
	fetch: worker.fetch,

	async scheduled(event, env, ctx) {
		// Daily pulls the Partner API; hourly only drains the merchant lifecycle
		// outbox, so a welcome email is not a day late.
		const task = event.cron === '0 3 * * *' ? 'all' : 'lifecycle';
		ctx.waitUntil(runCron(env, ctx, task));
	}
};
`
);

console.log('wrap-worker: added scheduled handler to worker.js');
